// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: internal/api/messages.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Reserved for future use
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_internal_api_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatResponse_Token
	//	*ChatResponse_Done
	//	*ChatResponse_Error
	Payload       isChatResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_internal_api_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetPayload() isChatResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatResponse) GetToken() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Token); ok {
			return x.Token
		}
	}
	return ""
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Done); ok {
			return x.Done
		}
	}
	return false
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isChatResponse_Payload interface {
	isChatResponse_Payload()
}

type ChatResponse_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"` // Streaming token
}

type ChatResponse_Done struct {
	Done bool `protobuf:"varint,2,opt,name=done,proto3,oneof"` // Stream complete signal
}

type ChatResponse_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // Error message
}

func (*ChatResponse_Token) isChatResponse_Payload() {}

func (*ChatResponse_Done) isChatResponse_Payload() {}

func (*ChatResponse_Error) isChatResponse_Payload() {}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_internal_api_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_internal_api_messages_proto_rawDescGZIP(), []int{2}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_internal_api_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_api_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_internal_api_messages_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *StatusResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_internal_api_messages_proto protoreflect.FileDescriptor

const file_internal_api_messages_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/api/messages.proto\x12\rcrabby.api.v1\"F\n" +
	"\vChatRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"_\n" +
	"\fChatResponse\x12\x16\n" +
	"\x05token\x18\x01 \x01(\tH\x00R\x05token\x12\x14\n" +
	"\x04done\x18\x02 \x01(\bH\x00R\x04done\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05errorB\t\n" +
	"\apayload\"\x0f\n" +
	"\rStatusRequest\"Z\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversionB/Z-github.com/marciniwanicki/crabby/internal/apib\x06proto3"

var (
	file_internal_api_messages_proto_rawDescOnce sync.Once
	file_internal_api_messages_proto_rawDescData []byte
)

func file_internal_api_messages_proto_rawDescGZIP() []byte {
	file_internal_api_messages_proto_rawDescOnce.Do(func() {
		file_internal_api_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_api_messages_proto_rawDesc), len(file_internal_api_messages_proto_rawDesc)))
	})
	return file_internal_api_messages_proto_rawDescData
}

var file_internal_api_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_internal_api_messages_proto_goTypes = []any{
	(*ChatRequest)(nil),    // 0: crabby.api.v1.ChatRequest
	(*ChatResponse)(nil),   // 1: crabby.api.v1.ChatResponse
	(*StatusRequest)(nil),  // 2: crabby.api.v1.StatusRequest
	(*StatusResponse)(nil), // 3: crabby.api.v1.StatusResponse
}
var file_internal_api_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_api_messages_proto_init() }
func file_internal_api_messages_proto_init() {
	if File_internal_api_messages_proto != nil {
		return
	}
	file_internal_api_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*ChatResponse_Token)(nil),
		(*ChatResponse_Done)(nil),
		(*ChatResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_api_messages_proto_rawDesc), len(file_internal_api_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_api_messages_proto_goTypes,
		DependencyIndexes: file_internal_api_messages_proto_depIdxs,
		MessageInfos:      file_internal_api_messages_proto_msgTypes,
	}.Build()
	File_internal_api_messages_proto = out.File
	file_internal_api_messages_proto_goTypes = nil
	file_internal_api_messages_proto_depIdxs = nil
}
